export default [
  {
    ignores: ["dist/**", "node_modules/**", "coverage/**"]
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "writable",
        document: "readonly",
        navigator: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        process: "readonly",
        fetch: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        HTMLElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLTextAreaElement: "readonly",
        Event: "readonly",
        CustomEvent: "readonly",
        IntersectionObserver: "readonly",
        Notification: "readonly",
        indexedDB: "readonly",
        confirm: "readonly",
        alert: "readonly",
        prompt: "readonly",
        NEXORA: "writable",
        self: "readonly",
        caches: "readonly",
        Response: "readonly",
        Chart: "readonly",
        jspdf: "readonly",
        jsPDF: "readonly",
        gantt: "readonly",
        Gantt: "readonly",
        frappe: "readonly",
        html2canvas: "readonly",
        __dirname: "readonly",
        crypto: "readonly",
        PMBOK_CATALOG: "readonly",
        PMBOK_GROUPS: "readonly",
        App: "readonly",
        showToast: "readonly",
        showView: "readonly",
        toggleNotifications: "readonly",
        renderDashboard: "readonly",
        renderProjects: "readonly",
        renderProjectDetail: "readonly",
        renderItemDetail: "readonly",
        renderApprovals: "readonly",
        renderCosts: "readonly",
        renderReports: "readonly",
        renderEmployeesView: "readonly",
        renderAdmin: "readonly",
        renderOwnerDashboard: "readonly",
        renderProcesses: "readonly",
        openProcessDetail: "readonly",
        renderProcessWizard: "readonly",
        renderProcessDashboard: "readonly",
        renderBOQ: "readonly",
        renderDailyLabor: "readonly",
        renderCashflow: "readonly",
        renderStakeholders: "readonly",
        renderContracts: "readonly",
        renderChangeRequests: "readonly",
        renderTurbo: "readonly",
        renderTurboDaily: "readonly",
        renderTurboPurchases: "readonly",
        renderTurboCashflow: "readonly",
        renderEntPlanning: "readonly",
        renderEntExecution: "readonly",
        renderEntControl: "readonly",
        renderAlertsCenter: "readonly",
        renderGantt: "readonly",
        openTaskModal: "readonly"
      }
    },
    rules: {
      "no-unused-vars": ["warn", { "argsIgnorePattern": "^_", "varsIgnorePattern": "^_" }],
      "no-undef": "error"
    }
  }
];
